
h = 0.64130933
T_cmb = 2.7255

n_s = 0.9710367439847746
tau_reio = 0.057
omega_b = 0.02238280
omega_cdm = 0.1201075
m_ncdm = 0.06
N_ncdm = 1
N_ur = 2.0308
A_s = 2.1327557162026904e-09
#A_s = 1.1184149159642895e-09


Omega_Lambda = 0
Omega_fld = 0 
Omega_smg = -1 


1) Quintomt theory:  G_2 -> X -V(phi),  
                         G_4 -> M_p^2/2 (1 + x phi^2)
                         
   Monomial potential:   V -> V0 + beta chi + m^2 chi^2
   Notes:  - small phi_ini fails to get enough Omega_DE
           - phi_prime_ini -> 0 causes an artificial instability (alpha_k->0)
             need to set small value or use a_min_stability_test_smg
   
gravity_model = quintom 
gravity_submodel = quintom_shift_alpha
M_pl_today_smg = -1
use_pert_var_deltaphi_smg = yes



#V0, beta, m2, lambda, alpha, phi_s, xi, phi0, dphi0

# Parameters in the following order

# V(phi) = V0 + beta * phi + m2/2 * phi^2 + lambda/4 phi^4

# phi_s ~ 0


# For these parameters phi_s_smg -> 1.00156 when alpha = 1
V0_smg = 6.141663 # 
beta_smg = 0
m2_smg = -11.403525	
mu_smg = 0.
lambda_smg = 1.489941


#M_pl_tuning_smg = yes


# Non minimal coupling function: G4 = 1/2 * (alpha + xi phi^2)
# alpha_smg = 1.134110 # Can be ignored for the moment
alpha_smg = 1.
phi_s_smg = 0.0
xi_smg = -10.947763


# Initial conditions for the scalar field
phi0_smg = 0.
dphi0_smg = 1e-4

tuning_index_smg = 8 # v0
tuning_dxdy_guess_smg = 1.0
# Problems at early universe
# cs2_safe_smg = 1


# 3a) The absence of ghost and gradient instabilities is tested in the code for both scalars
#     and tensors. It is possible to avoid these tests altoghether by changing

skip_stability_tests_smg = yes

# 3b) If skip_stability_tests_smg is set to no, it is possible to relax the stability conditions
#     to accept slightly negative values  (moslty to avoid numerical noise around 0).
#     Indeed, the code internally verify that the following conditions are satisfied at all times
#     i)    cs2_smg > - abs(cs2_safe_smg). Sound speed of the scalar sector
#     ii)   ct2_smg > - abs(ct2_safe_smg). Sound speed of the tensor sector
#     iii)  D_smg > - abs(D_safe_smg). Kinetic term of the scalar sector
#     iv)   M2_smg > - abs(M2_safe_smg). Kinetic term of the tensor sector
#     Negative values skip a test altogether (all default values are zero)

cs2_safe_smg = 0.
D_safe_smg = 0.
ct2_safe_smg = 0.
M2_safe_smg = 0.



# 3c) It is also possible to omit stability tests before a certain scale factor (default 0).
#     Useful for models where the stability failure is due to numerical errors (e.g. brans_dicke)

a_min_stability_test_smg = 1e-2

# 3d) Mathematical stability conditions to test the presence of exponentially growing modes in the 
#     perturbations. This follows closely the EFTCAMB implementation detailed in 1405.3590
#     Here we add the parameter 'exp_rate' to control the largest accepted growth rate in units of H0

# =================================================
# =================================================
# ============= PERTUBATION SETTINGS
# =================================================
# =================================================
output = tCl,pCl,lCl,mTk,mPk
#l_max_scalars =  3000
lensing =  yes
non_linear = hmcode 
#nonlinear_min_k_max = 25
skip_math_stability_smg = yes
exp_rate_smg = 1.

use_ppf = yes

# -------------------------------------------------
# ----> perturbation initial conditions parameters:
# -------------------------------------------------

# 5a) There are two possible initial conditions for the perturbations of the scalar field
#     i)     "ext_field_attr": assumes that scalar does not gravitate (no modified gravity) at early times
#            but only follows the superhorizon potential created by radiation (default)
#     ii)    "gravitating_attr": allows the scalar to gravitate (gravity is modified) at early times
#            modifying the superhorizon evolution of other species.
#     iii)   "single_clock": single_clock IC given with respect to photons
#     iv)    "zero": set the initial value of the scalar field and its first derivative to 0

pert_initial_conditions_smg = gravitating_attr

# 5b) Precision parameters used to set/test initial conditions: for certain choices of parameters models, 
#     it may well be that a new fast growing mode appears. This would then dominate the initial evolution 
#     and decouple the initial conditions from those given by inflation. We test to disallow such situations.
#     i)     pert_ic_ini_z_ref_smg -> redshift at which initial IC stability test performed */
#     ii)    pert_ic_tolerance_smg -> tolerance to deviations from standard ICs h~tau^2 as evaluated at redshift pert_ic_ini_z_ref_smg (negative values override test)
#     iii)   pert_ic_regulator_smg -> minimum size of denominator in IC expressions: regulate to prevent infinities (negative values set off regulator)
#     iv)    pert_qs_ic_tolerance_test_smg -> Max contribution of QS SMG at superhorizon scales to zeta non-conservation as fraction of standard contributon from radiation
    
    
pert_ic_ini_z_ref_smg = 1e10    
pert_ic_tolerance_smg = 2e-2 
pert_ic_regulator_smg = 1e-15
pert_qs_ic_tolerance_test_smg = 10
    

# --------------------------------------------
# ----> quasi-static approximation parameters:
# --------------------------------------------

# 6a) This function set the method used for the qs_smg approximation during the run of the code.
#     The options are:
#     i)    "automatic" -> uses the approximation scheme implemented
#     ii)   "fully_dynamic" -> forces the fully-dynamical evolution of the perturbations at all times (default)
#     iii)  "quasi_static" -> forces the quasi-static evolution of the perturbations at all times (doesn't work for stable_params)
#     iv)   "fully_dynamic_debug" -> forces the fully-dynamic evolution but evaluates the approximation scheme
#     v)    "quasi_static_debug" -> forces the quasi-static evolution but evaluates the approximation scheme

method_qs_smg = automatic #fully_dynamic

# 6b) Precision parameters used in the quasi-static approximation (only if "automatic" is used)
#     i)    z_fd_qs_smg -> minimum redshift after which the user requires the fully-dynamic evolution
#     ii)   trigger_mass_qs_smg -> minimum effective mass above which the quasi-static approximation is switched on
#     iii)  trigger_rad_qs_smg -> minimum radiation trigger for quasi-static approximation
#     iv)   eps_s_qs_smg -> minimum relative decay of oscillating solution before switching on quasi-static approximation
#     Note that all the conditions need to be satisfied for the quasi-static approximation to be used

z_fd_qs_smg = 0. 
trigger_mass_qs_smg = 1.e2
trigger_rad_qs_smg = 1.e2
eps_s_qs_smg = 0.01

# 6c) Sampling to determine intervals for quasi-static approximation. Must be typed as an integer, no exponential form!
#     i)    n_min_qs_smg -> minimum number of steps used to sample quantities in the quasi-static approximation 
#     ii)   n_max_qs_smg -> maximum number of steps used to sample quantities in the quasi-static approximation 
    
n_min_qs_smg = 100 
n_max_qs_smg = 10000 

# ---------------------------
# ----> precision parameters:
# ---------------------------

# 7a) Sometimes the evolution of the perturbations is slown down due to the presence of rapid
#     oscillations of the scalar field at early times. We noticed that it is possible to speed
#     up the code by artificially adding a constant value to the kineticity. This should not
#     affect observable scales, but you use it at your own risk! (default: 0.)
#     NOTE: it is advised to use a QS approximation instead (after V2)

kineticity_safe_smg = 0.

# 7b) When studying early dark energy models, sometimes the code complaints if radiation is
#     not sufficiently dominant at early times. Then, you can try to modify the CLASS precision
#     parameter tol_initial_Omega_r (default: 1.e-4)

# tol_initial_Omega_r = 1.e-4

# 7c) We noticed that some precision parameter of CLASS has to be modified to get precise enough
#     results in hi_class. We then changed their default values in "source/input.c". These are

start_small_k_at_tau_c_over_tau_h = 1e-4
start_large_k_at_tau_h_over_tau_k = 1e-4
perturbations_sampling_stepsize = 0.01 #0.01 #(high precision) #0.03 #(standard precision) 
l_logstep = 1.026 #1.026 #(high precision) #1.045 #(standard precision) 
l_linstep = 25
k_max_tau0_over_l_max = 8. #(high precision) #comment for standard precision
k_per_decade_for_pk = 200 #200 #(high precision) #30 #(standard precision)

ncdm_fluid_approximation = #3 #(high precision) #1 #(standard precision)
# tol_ncdm_synchronous = 1e-5
# tol_ncdm = 1e-3


------ other parameters --------

root = output/quintom_root_test_

output_background_smg = 10
write parameters = yes
write background = yes
write perturbation = no
#write thermodynamics = yes
#k_output_values = 1., 0.1, 0.01, 0.0001

#input_verbose = 4
#background_verbose = 4
#output_verbose = 1
#thermodynamics_verbose = 1
#perturbations_verbose = 2
#spectra_verbose = 2

#non linear = hmcode
#nonlinear_min_k_max = 25

input_verbose = 3
background_verbose = 3
output_verbose = 0
thermodynamics_verbose = 0
perturbations_verbose = 0
spectra_verbose = 0

#tol_shooting_deltax_rel = 1e-7
